import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import FirstNav from '@/components/FirstNav';
import MainNav from '@/components/MainNav';
import MainFooter from '@/components/MainFooter';
import SecFooter from '@/components/SecFooter';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <FirstNav />
        <MainNav />
        {children}
        <MainFooter />
        <SecFooter />
      </body>
    </html>
  );
}
